name: billionaires_scrape

on:
  schedule:
    - cron: '0 5 * * *'  # every_day at  05:00 am


jobs:
  billionaires_scrape:
    runs-on: macos-latest
    env:
      ATLAS_COLLECTION1: ${{ secrets.ATLAS_COLLECTION1 }}
      ATLAS_COLLECTION2: ${{ secrets.ATLAS_COLLECTION2 }}
      ATLAS_COLLECTION3: ${{ secrets.ATLAS_COLLECTION3 }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)' 
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install jsonlite package
        run: Rscript -e 'install.packages("jsonlite", dependencies = TRUE)'
      - name: Scrape data 
        run: Rscript scrape.R
